import React from 'react'; // Import React
import './globals.css';
import { Inter } from 'next/font/google';
import { AuthUserProvider } from '../../firebase/Auth'; // Correct import name
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add your head elements here */}
      </head>
      <body className={inter.className}>
      <ToastContainer position="top-center" />
        <AuthUserProvider>{children}</AuthUserProvider> 
      </body>
    </html>
  );
}
